
// 
REGISTER_NAME(0, None)
REGISTER_NAME(1, MainBoard)
REGISTER_NAME(20, Z80)
REGISTER_NAME(30, ULA)
REGISTER_NAME(31, Display)
REGISTER_NAME(40, AccessToROM)
REGISTER_NAME(50, Memory)
REGISTER_NAME(51, EPROM)
REGISTER_NAME(52, DRAM)

REGISTER_NAME(100, FileDialog)
REGISTER_NAME(101, Canvas)
REGISTER_NAME(102, Palette)
REGISTER_NAME(103, ToolBar)
REGISTER_NAME(104, StatusBar)
REGISTER_NAME(105, SpriteList)
REGISTER_NAME(106, SpriteMetadata)
